var canvas,stage,renderer,jvgame_WIDTH=1080,jvgame_HEIGHT=1080,jvgame_states={PLAYING:0,STOPPED:1},jvgame_state,jvgame_time_delta,jvgame_time_smoothdelta,jvgame_time_previous,jvgame_time_framecount=0,jvgame_current_timestamp_indexes=[],jvgame_pre_time=1,jvgame_current_difficulty_index=2,jvgame_pool_amount=30,jvgame_pool_pills=[],jvgame_pool_current_index=-1,jvgame_pool_kill_queue=[],jvgame_anchor_spawn={x:void 0,y:void 0},jvgame_anchor_death={x:void 0,y:void 0},jvgame_anchor_death_animation={x:void 0,
y:void 0},jvgame_anchor_middle={x:void 0,y:void 0},jvgame_anchor_combo_feedback={x:void 0,y:void 0},jvgame_sprite_debug_anchor_spawn,jvgame_sprite_debug_anchor_death,jvgame_sprite_debug_anchor_death_animation,jvgame_sprite_debug_anchor_combo_feedback,jvgame_sprite_ui_button_shake,jvgame_sprite_ui_circle,jvgame_sprite_ui_smear,jvgame_sprite_ui_tictacbox,jvgame_sprite_ui_level_ring,jvgame_text_bonus_score,jvgame_element_pill,jvgame_element_ui_button_shake,jvgame_element_ui_circle,jvgame_element_ui_woofer,
jvgame_element_ui_horizontal_line,jvgame_element_ui_vertical_line,jvgame_element_ui_smear,jvgame_element_ui_tictacbox,jvgame_element_ui_level_ring,jvgame_element_debug_anchor_area,jvgame_element_debug_anchor_spawn,jvgame_element_debug_anchor_middle,jvgame_element_debug_anchor_death,jvgame_element_debug_anchor_death_animation,jvgame_element_debug_anchor_combo_feedback,jvgame_element_label_area,jvgame_element_label_score,jvgame_element_label_level,jvgame_element_label_bonus,jvgame_element_label_number_bubble,
jvgame_element_label_number_bubble_margin,jvgame_element_label_bg,jvgame_element_label_bg_slant,jvgame_element_label_bonus_score,jvgame_element_heart_area,jvgame_element_heart,jvgame_element_pilldance_amp,jvgame_element_particle_bubble,jvgame_element_countdown_number,jvgame_element_particle_origin,jvgame_player=new JVPlayer,jvgame_combo_feedback,jvgame_combo_font_size=void 0,jvgame_label_score,jvgame_label_level,jvgame_label_bonus,jvgame_label_hearts,jvgame_color_text=2168105,jvgame_color_combo_feedback_positive=
15594306,jvgame_color_combo_feedback_negative=15876417,jvgame_color_bubble_bg=2168105,jvgame_color_bubble_text=16777215,jvgame_color_label_bg=16777215,jvgame_color_label_fill=1228639,jvgame_color_bonus_score=2168105,jvgame_color_circle_begin=16777215,jvgame_color_circle_end=16771584,jvgame_color_circle_red=16711680,jvgame_color_countdown=15594306,jvgame_color_circle_array=[16444160,252926,16774762,32511,9496386,4374247,15971598,4344551,15155922,12583167],jvgame_color_score_text_white=2168105,jvgame_color_score_text_yellow=
15594306,jvgame_color_score_text_red=15876417,jvgame_pillsine_amp=50,jvgame_countdown,jvgame_current_circle_color,jvgame_copy=new JVCopy,jvgame_particle_manager=new JVParticleManager,jvgame_scoretext_manager=new JVScoreTextManager,debug_show_anchors=!1,debug_show_areas=!1;
function jvgame_setup(a,b){jvgame_WIDTH=a;jvgame_HEIGHT=b;jvgame_setup_screen_elements();stage=new PIXI.Container;renderer=PIXI.autoDetectRenderer(jvgame_WIDTH,jvgame_HEIGHT,{antialias:!1,transparent:!0,resolution:window.devicePixelRatio||1});document.getElementById("canvas_container").appendChild(renderer.view);canvas=document.getElementsByTagName("canvas");PIXI.loader.add(ASSET_FOLDER+"/img/sheet.json").load(jvgame_finish_texture_load);jvgame_pool_init()}
function jvgame_finish_texture_load(){jvgame_setup_sprites();jvgame_setup_finish()}
function jvgame_setup_screen_elements(){var a={screen_size:{x:jvgame_WIDTH,y:jvgame_HEIGHT},screen_position:{x:jvgame_WIDTH/2,y:jvgame_HEIGHT/2}};jvgame_element_pill=new JVScreenElement2(a,{x:-1,y:-1},.1,void 0,{x:1,y:1});jvgame_element_ui_button_shake=new JVScreenElement2(a,{x:.5,y:.86},.2,void 0,{x:1,y:1});jvgame_element_ui_circle=new JVScreenElement2(a,{x:.5,y:.475},.8,1.2,{x:1,y:1});jvgame_element_ui_woofer=new JVScreenElement2(a,{x:.5,y:.475},.45,1.2,{x:1,y:1});jvgame_element_ui_smear=new JVScreenElement2(a,
{x:.475,y:.84},.5,.9,{x:10,y:1.5});jvgame_element_ui_tictacbox=new JVScreenElement2(a,{x:.35,y:.8},.4,.35,{x:19,y:32});jvgame_element_ui_level_ring=new JVScreenElement2(jvgame_element_ui_woofer,{x:.5,y:.5},.9,.9,{x:1,y:1});jvgame_element_ui_horizontal_line=new JVScreenElement2(a,{x:.5,y:.475},.005,void 0,{x:150,y:1});jvgame_element_ui_vertical_line=new JVScreenElement2(a,{x:.5,y:.475},.2,void 0,{x:1,y:50});jvgame_element_debug_anchor_area=new JVScreenElement2(a,{x:.5,y:.475},.75,void 0,{x:1,y:1});
jvgame_element_debug_anchor_spawn=new JVScreenElement2(jvgame_element_debug_anchor_area,{x:1,y:.5},.05,void 0,{x:1,y:1});jvgame_element_debug_anchor_middle=new JVScreenElement2(jvgame_element_debug_anchor_area,{x:.5,y:.5},.05,void 0,{x:1,y:1});jvgame_element_debug_anchor_death=new JVScreenElement2(jvgame_element_debug_anchor_area,{x:0,y:.5},.05,void 0,{x:1,y:1});jvgame_element_debug_anchor_death_animation=new JVScreenElement2(jvgame_element_debug_anchor_area,{x:.1,y:.5},.05,void 0,{x:1,y:1});jvgame_element_debug_anchor_combo_feedback=
new JVScreenElement2(jvgame_element_debug_anchor_area,{x:.5,y:.275},.05,void 0,{x:1,y:1});jvgame_anchor_spawn.x=jvgame_element_debug_anchor_spawn.screen_position.x;jvgame_anchor_spawn.y=jvgame_element_debug_anchor_spawn.screen_position.y;jvgame_anchor_middle.x=jvgame_element_debug_anchor_middle.screen_position.x;jvgame_anchor_middle.y=jvgame_element_debug_anchor_middle.screen_position.y;jvgame_anchor_death.x=jvgame_element_debug_anchor_death.screen_position.x;jvgame_anchor_death.y=jvgame_element_debug_anchor_death.screen_position.y;
jvgame_anchor_death_animation.x=jvgame_element_debug_anchor_death_animation.screen_position.x;jvgame_anchor_death_animation.y=jvgame_element_debug_anchor_death_animation.screen_position.y;jvgame_anchor_combo_feedback.x=jvgame_element_debug_anchor_combo_feedback.screen_position.x;jvgame_anchor_combo_feedback.y=jvgame_element_debug_anchor_combo_feedback.screen_position.y;jvgame_element_label_area=new JVScreenElement2(a,{x:.5,y:.1},.15,.9,{x:5,y:1});jvgame_element_label_score=new JVScreenElement2(jvgame_element_label_area,
{x:.5,y:.2},.75,void 0,{x:1,y:1});jvgame_element_label_level=new JVScreenElement2(jvgame_element_label_area,{x:.17,y:.8},.75,void 0,{x:1,y:1});jvgame_element_label_bonus=new JVScreenElement2(jvgame_element_label_area,{x:.83,y:.8},.75,void 0,{x:1,y:1});jvgame_element_label_bonus_score=new JVScreenElement2(jvgame_element_label_area,{x:.9,y:1.2},.3,.05,{x:1,y:1});jvgame_element_label_bg=new JVScreenElement2(a,{x:-1,y:-1},.05,.16,{x:2.7,y:1});jvgame_element_label_bg_slant=new JVScreenElement2(a,{x:-1,
y:-1},.005,.01,{x:1,y:1});jvgame_element_label_number_bubble=new JVScreenElement2(a,{x:0,y:0},.05,.07,{x:1,y:1});jvgame_element_number_bubble_margin=new JVScreenElement2(a,{x:-1,y:-1},.04,.07,{x:1,y:1});jvgame_element_heart_area=new JVScreenElement2(jvgame_element_label_area,{x:.475,y:.8},.4,void 0,{x:1,y:.5});jvgame_element_heart=new JVScreenElement2(jvgame_element_label_area,{x:1,y:1},.25,.1,{x:1,y:1});jvgame_element_particle_origin=new JVScreenElement2(jvgame_element_ui_woofer,{x:.5,y:.5},.4,.5,
{x:1,y:1});jvgame_element_particle_bubble=new JVScreenElement2(a,{x:-1,y:-1},.1,.3,{x:1,y:1});jvgame_element_pilldance_amp=new JVScreenElement2(jvgame_element_label_area,{x:-1,y:-1},.2,void 0,{x:1,y:.5});jvgame_element_countdown_number=new JVScreenElement2(jvgame_element_ui_circle,{x:.5,y:.35},.5,1.2,{x:1,y:1})}
function jvgame_setup_sprites(){jvgame_sprite_ui_circle=new PIXI.Sprite(PIXI.TextureCache["ui_circle.png"]);jvgame_sprite_ui_woofer=new PIXI.Sprite(PIXI.TextureCache["ui_woofer.png"]);jvgame_sprite_ui_button_shake=new PIXI.Sprite(PIXI.TextureCache["ui_button_shake.png"]);jvgame_sprite_ui_smear=new PIXI.Sprite(PIXI.TextureCache["ui_smear.png"]);jvgame_sprite_ui_tictacbox=new PIXI.Sprite(PIXI.TextureCache["ui_tictacbox.png"]);jvgame_sprite_ui_level_ring=new PIXI.Sprite(PIXI.TextureCache["ui_level_ring.png"]);
debug_show_anchors&&(jvgame_sprite_debug_anchor_spawn=new PIXI.Sprite(PIXI.TextureCache["debug_anchor.png"]),jvgame_sprite_debug_anchor_death=new PIXI.Sprite(PIXI.TextureCache["debug_anchor.png"]),jvgame_sprite_debug_anchor_death_animation=new PIXI.Sprite(PIXI.TextureCache["debug_anchor.png"]),jvgame_sprite_debug_anchor_combo_feedback=new PIXI.Sprite(PIXI.TextureCache["debug_anchor.png"]));jvgame_setup_single_sprite(jvgame_element_ui_circle,jvgame_sprite_ui_circle);jvgame_particle_manager.init();
jvgame_setup_single_sprite(jvgame_element_ui_level_ring,jvgame_sprite_ui_level_ring);jvgame_setup_single_sprite(jvgame_element_ui_woofer,jvgame_sprite_ui_woofer);jvgame_setup_single_sprite(jvgame_element_ui_smear,jvgame_sprite_ui_smear);var a=new PIXI.Graphics;a.lineStyle(jvgame_element_ui_horizontal_line.screen_size.y,16777215,1);a.moveTo(jvgame_element_ui_horizontal_line.screen_position.x-jvgame_element_ui_horizontal_line.screen_size.x/2,jvgame_element_ui_horizontal_line.screen_position.y);a.lineTo(jvgame_element_ui_horizontal_line.screen_position.x+
jvgame_element_ui_horizontal_line.screen_size.x/2,jvgame_element_ui_horizontal_line.screen_position.y);a.position.set(0,0);stage.addChild(a);a=new PIXI.Graphics;a.lineStyle(jvgame_element_ui_vertical_line.screen_size.x,16777215,1);a.moveTo(jvgame_element_ui_vertical_line.screen_position.x,jvgame_element_ui_vertical_line.screen_position.y-jvgame_element_ui_vertical_line.screen_size.y/2);a.lineTo(jvgame_element_ui_vertical_line.screen_position.x,jvgame_element_ui_vertical_line.screen_position.y+jvgame_element_ui_vertical_line.screen_size.y/
2);a.position.set(0,0);stage.addChild(a);jvgame_setup_single_sprite(jvgame_element_ui_tictacbox,jvgame_sprite_ui_tictacbox);jvgame_sprite_ui_tictacbox.anchor.set(1,1);jvgame_sprite_ui_button_shake.interactive=!0;jvgame_sprite_ui_button_shake.buttonMode=!0;jvgame_setup_single_sprite(jvgame_element_ui_button_shake,jvgame_sprite_ui_button_shake);debug_show_anchors&&(debug_show_areas&&jvgame_setup_single_area(jvgame_element_debug_anchor_area,16711680),jvgame_setup_single_sprite(jvgame_element_debug_anchor_death,
jvgame_sprite_debug_anchor_death,16733440),jvgame_setup_single_sprite(jvgame_element_debug_anchor_death_animation,jvgame_sprite_debug_anchor_death_animation,16733440),jvgame_setup_single_sprite(jvgame_element_debug_anchor_spawn,jvgame_sprite_debug_anchor_spawn,65280),jvgame_setup_single_sprite(jvgame_element_debug_anchor_combo_feedback,jvgame_sprite_debug_anchor_combo_feedback,16776960));debug_show_areas&&jvgame_setup_single_area(jvgame_element_label_area,65280);jvgame_label_score=new JVScoreLabel(jvgame_element_label_score,
7,jvgame_copy.get("score"));jvgame_label_level=new JVScoreLabel(jvgame_element_label_level,2,jvgame_copy.get("niveau"));jvgame_label_bonus=new JVScoreLabel(jvgame_element_label_bonus,3,jvgame_copy.get("bonus"));jvgame_text_bonus_score=new PIXI.Text("+BONUS",{fontFamily:"UniSans",fontSize:jvgame_element_label_bonus_score.screen_size.y,fill:jvgame_color_bonus_score});jvgame_text_bonus_score.anchor.set(.5,.5);jvgame_text_bonus_score.position.set(jvgame_element_label_bonus_score.screen_position.x,jvgame_element_label_bonus_score.screen_position.y);
stage.addChild(jvgame_text_bonus_score);debug_show_areas&&jvgame_setup_single_area(jvgame_element_heart_area,16751561)}function jvgame_setup_single_sprite(a,b,c){b.anchor.set(.5,.5);b.position.set(a.screen_position.x,a.screen_position.y);b.width=a.screen_size.x;b.height=a.screen_size.y;"undefined"!==typeof c&&(b.tint=c);stage.addChild(b)}
function jvgame_setup_single_area(a,b){var c=new PIXI.Graphics;c.lineStyle(3,b,1);c.drawRect(a.screen_position.x-a.screen_size.x/2,a.screen_position.y-a.screen_size.y/2,a.screen_size.x,a.screen_size.y);stage.addChild(c)}function jvgame_setup_events(){jvgame_sprite_ui_button_shake.on("pointerdown",function(a){jvgame_input_shake()})}function jvgame_setup_time(){jvgame_time_previous=performance.now();jvgame_time_smoothdelta=0}function jvgame_setup_language(){}
function jvgame_setup_finish(){jvgame_setup_time();jvgame_setup_events();jvgame_combo_feedback=new JVComboFeedback;jvgame_combo_feedback.init();jvgame_countdown=new JVCountdownNumber;jvgame_countdown.init();jvgame_label_hearts=new JVHeartLabel(jvgame_element_heart_area,3);jvmain_set_setup_ready_flag("game",!0)}
function jvgame_start(){jvgame_player.init();jvgame_update_combo_score_text();jvaudio_play_song();jvgame_countdown.begin();jvgame_combo_feedback.stop();jvgame_state=jvgame_states.PLAYING;requestAnimationFrame(jvgame_update)}
function jvgame_update(){requestAnimationFrame(jvgame_update);jvgame_time_framecount++;jvgame_time_delta=(performance.now()-jvgame_time_previous)/1E3;jvgame_time_smoothdelta+=.5*(jvgame_time_delta-jvgame_time_smoothdelta);jvgame_time_previous=performance.now();jvaudio_update();jvgame_state==jvgame_states.PLAYING?state_game():jvgame_state==jvgame_states.STOPPED&&state_stopped();renderer.render(stage)}
function jvgame_stop(){jvgame_state=jvgame_states.STOPPED;jvgame_pool_kill_all();jvgame_countdown.stop();jvanimation_animations=[];jvgame_combo_feedback.stop();jvgame_particle_manager.stop();jvaudio_current_song.stop();midi_manager.reset_timestamp_indexes();jvmain_end_session();jvmain_session_ready_flags.user=!1;jvmain_show_endscreen()}function state_menu(){}
function state_game(){var a=jvaudio_get_current_timestamp(),b=midi_manager.get_current_song();jvgame_countdown.isActive&&jvgame_countdown.update();jvgame_particle_manager.update();for(var c=0;c<b.tracks.length;c++){var d=b.tracks[c].current_timestamp_index,e=b.tracks[c].timestamps[d];if(a>=e-jvgame_pre_time){if(c==jvgame_player.difficulty_level){for(var f=b.tracks[c].pill_types[d],g=0;g<jvgame_pool_pills.length;g++)jvgame_pool_pills[g].timestamp==e&&jvgame_pool_add_to_kill_queue(jvgame_pool_pill[g].pool_id);
jvgame_pool_spawn(d,f,e)}b.tracks[c].current_timestamp_index++}}for(c=0;c<jvgame_pool_pills.length;c++)b=jvgame_pool_pills[c],b.flag_pool_alive&&(b.update(),b.flag_hit&&!b.flag_death_animation_playing&&b.position.x<=jvgame_anchor_death_animation.x&&(b.flag_death_animation_playing=!0,jvanimation_add(jvanimation_pill_kill(b))),b.position.x<=jvgame_anchor_death.x&&jvgame_pool_add_to_kill_queue(b.pool_id),!b.flag_crossed&&a>=b.timestamp+jvgame_player.time_deviation&&(b.flag_crossed=!0,b.flag_hit||(d=
new JVEvent(a),d.pill_missed(jvgame_player.difficulty_level,b.track_index,b.flag_misplaced),d.submit(),jvanimation_add(jvanimation_pill_missed(b)),2!=b.type&&jvgame_player.combo_reset())),jvgame_pool_purge_kill_queue());jvanimation_update();jvgame_player.update_timer()}function state_stopped(){}function jvgame_show_combo_feedback(a,b){jvgame_combo_feedback.show(a,b)}var keySpace=keyboard(32),keyMute=keyboard(77);keyMute.press=function(){jvaudio_toggle_mute()};
document.onkeyup=function(a){console.log("keyCode: "+a.keyCode)};
function keyboard(a){var b={};b.code=a;b.isDown=!1;b.isUp=!0;b.press=void 0;b.release=void 0;b.downHandler=function(a){a.keyCode===b.code&&(b.isUp&&b.press&&b.press(),b.isDown=!0,b.isUp=!1);a.preventDefault()};b.upHandler=function(a){a.keyCode===b.code&&(b.isDown&&b.release&&b.release(),b.isDown=!1,b.isUp=!0);a.preventDefault()};window.addEventListener("keydown",b.downHandler.bind(b),!1);window.addEventListener("keyup",b.upHandler.bind(b),!1);return b}
function jvgame_input_shake(){jvanimation_add(jvanimation_button_shake_click());if(!jvgame_countdown.isActive&&0!=jvaudio_get_current_timestamp()){for(var a=jvaudio_get_current_timestamp(),b=!1,c=new JVEvent(a),d=0;d<jvgame_pool_pills.length;d++)if(!jvgame_pool_pills[d].flag_crossed){var e=Math.abs(jvgame_pool_pills[d].timestamp-a);!b&&e<=jvgame_player.time_deviation&&0!=jvgame_pool_pills[d].flag_active&&(jvgame_pool_pills[d].flag_active=!1,jvgame_pool_pills[d].flag_hit=!0,0==jvgame_pool_pills[d].type?
(jvaudio_play_shake(),jvaudio_set_current_song_volume(!0),c.user_tap(!0,jvgame_pool_pills[d].track_index,jvgame_player.difficulty_level,0,jvgame_pool_pills[d].timestamp,jvgame_pool_pills[d].flag_misplaced),c.submit(),jvgame_player.score_update(jvgame_player.score_amounts.white),jvgame_player.combo_update(1),jvanimation_add(jvanimation_circle_scale())):1==jvgame_pool_pills[d].type?(jvaudio_play_shake(),jvaudio_set_current_song_volume(!0),c.user_tap(!0,jvgame_pool_pills[d].track_index,jvgame_player.difficulty_level,
1,jvgame_pool_pills[d].timestamp,jvgame_pool_pills[d].flag_misplaced),c.submit(),jvgame_player.score_update(jvgame_player.score_amounts.yellow),jvgame_player.combo_update(1),jvanimation_add(jvanimation_circle_scale()),jvgame_particle_manager.trigger()):2==jvgame_pool_pills[d].type&&(jvaudio_play_fail(),c.user_tap(!0,jvgame_pool_pills[d].track_index,jvgame_player.difficulty_level,2,jvgame_pool_pills[d].timestamp,jvgame_pool_pills[d].flag_misplaced),c.submit(),jvgame_player.score_update(jvgame_player.score_amounts.red),
jvgame_player.combo_reset(),jvgame_show_combo_feedback(!1,jvgame_player.score_amounts.red),jvanimation_add(jvanimation_circle_red())),b=!0,jvanimation_add(jvanimation_pill_hit(jvgame_pool_pills[d])))}b||(c.user_tap(!1,void 0,void 0,void 0,void 0,void 0),c.submit(),jvgame_player.score_update(jvgame_player.score_amounts.fail),jvgame_player.life_update(+1),jvgame_player.combo_reset(),jvaudio_play_fail(),jvaudio_set_current_song_volume(!1),jvgame_show_combo_feedback(!1,jvgame_player.score_amounts.fail),
jvanimation_add(jvanimation_circle_red()))}}function jvgame_pool_init(){for(var a=0;a<jvgame_pool_amount;a++)jvgame_pool_pills[a]=new JVPill,jvgame_pool_pills[a].pool_spawn()}
function jvgame_pool_spawn(a,b,c){for(var d=-1,e=0;e<jvgame_pool_pills.length;e++)if(0==jvgame_pool_pills[e].flag_pool_alive){d=e;break}-1==d?console.log("\u26a0\ufe0f Pool array was full, dropping current pill. Try increasing the pool amount."):(jvgame_pool_current_index=(jvgame_pool_current_index+1)%jvgame_pool_amount,jvgame_pool_pills[d].init(a,jvgame_pool_current_index,b,c),jvanimation_add(jvanimation_pill_spawn(jvgame_pool_pills[d])))}
function jvgame_pool_add_to_kill_queue(a){jvgame_pool_kill_queue.push(a)}function jvgame_pool_kill_all(){for(var a=0;a<jvgame_pool_pills.length;a++)jvgame_pool_add_to_kill_queue(jvgame_pool_pills[a].pool_id)}function jvgame_pool_purge_kill_queue(){for(var a=0;a<jvgame_pool_kill_queue.length;a++)for(var b=jvgame_pool_kill_queue[a],c=0;c<jvgame_pool_pills.length;c++)if(jvgame_pool_pills[c].pool_id==b){jvgame_pool_pills[c].kill();break}jvgame_pool_kill_queue=[]}
function jvgame_function_reset_combo_text(){jvgame_update_combo_score_text()}function jvgame_update_combo_score_text(){if(jvgame_player.combo_finished)jvgame_text_bonus_score.text="";else{var a=midi_manager.get_current_song().bonus_data[jvgame_player.bonus_index].score;jvgame_text_bonus_score.text="+"+a}}
function jvgame_update_circle(){var a=map(jvgame_player.score,midi_manager.current_song.level_scores[jvgame_player.level-1],midi_manager.current_song.level_scores[jvgame_player.level],0,1);a=Math.min(a,1);var b=jvgame_sprite_ui_circle.width;a=map(a,0,1,jvgame_element_ui_circle.screen_size.x,1.5*jvgame_element_ui_circle.screen_size.x);jvanimation_add(jvanimation_circle_grow(b,a))}
function JVPill(){this.track_index=void 0;this.pool_id=-1;this.flag_pool_alive=!1;this.type=void 0;this.flag_crossed=!1;this.flag_active=!0;this.flag_death_animation_playing=this.flag_hit=!1;this.progress=this.timestamp=this.sprite=void 0;this.position={x:0,y:0};this.pool_spawn=function(){this.sprite=new PIXI.Sprite(PIXI.TextureCache["pill_0_0.png"]);this.sprite.anchor.set(.5,.5);stage.addChild(this.sprite)};this.init=function(a,b,c,d){this.track_index=a;this.pool_id=b;this.flag_pool_alive=!0;this.type=
c;this.flag_crossed=!1;this.flag_active=!0;this.sprite.texture=this.init_get_sprite_texture();this.sprite.width=jvgame_element_pill.screen_size.x;this.sprite.height=jvgame_element_pill.screen_size.y;this.sprite.position.set(jvgame_anchor_spawn.x,jvgame_anchor_spawn.y);this.sprite.rotation=0;stage.removeChild(this.sprite);stage.addChild(this.sprite);this.timestamp=d;this.position.x=jvgame_anchor_spawn.x;this.position.y=jvgame_anchor_spawn.y;this.flag_misplaced=!1};this.init_get_sprite_texture=function(){switch(this.type){case 0:var a=
PIXI.TextureCache["pill_0_0.png"];break;case 1:a=PIXI.TextureCache["pill_1_"+Math.round(3*Math.random())+".png"];break;case 2:a=PIXI.TextureCache["pill_2_0.png"]}return a};this.update=function(){var a=this.timestamp-jvgame_pre_time,b=this.timestamp+jvgame_pre_time;this.position.x=map(jvaudio_get_current_timestamp(),a,b,jvgame_anchor_spawn.x,jvgame_anchor_death.x);this.position.y=map(jvaudio_get_current_timestamp(),a,b,jvgame_anchor_spawn.y,jvgame_anchor_death.y);a=map(this.position.x,jvgame_anchor_spawn.x,
jvgame_anchor_middle.x,0,1);this.position.y+=Math.sin(2*map(this.position.x,jvgame_anchor_spawn.x,jvgame_anchor_death.x,0,6.283))*jvgame_element_pilldance_amp.screen_size.y*a;this.sprite.position.set(this.position.x,this.position.y)};this.kill=function(){this.pool_id=-1;this.flag_pool_alive=!1;this.type=void 0;this.flag_crossed=!1;this.flag_active=!0;this.flag_death_animation_playing=this.flag_hit=!1;stage.removeChild(this.sprite);this.progress=this.timestamp=void 0;this.position={x:0,y:0}}}
function JVScreenElement(a,b,c,d){this.reference_canvas_size={x:jvmain_reference_resolution.x,y:jvmain_reference_resolution.y};this.reference_pos={x:a,y:b};this.reference_size={x:c,y:d};this.screen_size={x:this.reference_size.x/this.reference_canvas_size.x*jvgame_WIDTH,y:this.reference_size.y/this.reference_canvas_size.y*jvgame_HEIGHT};this.screen_position={x:this.reference_pos.x/this.reference_canvas_size.x*jvgame_WIDTH,y:this.reference_pos.y/this.reference_canvas_size.y*jvgame_HEIGHT}}
function JVScreenElement2(a,b,c,d,e){this.parent=null==a?{screen_size:{x:jvgame_WIDTH,y:jvgame_HEIGHT},screen_position:{x:jvgame_WIDTH/2,y:jvgame_HEIGHT/2}}:{screen_position:{x:a.screen_position.x-a.screen_size.x/2,y:a.screen_position.y-a.screen_size.y/2},screen_size:a.screen_size};this.pos_pct={x:b.x,y:b.y};this.height_pct=c;this.size_x_max_pct=d;this.size_proportion={x:e.x,y:e.y};a=this.parent.screen_size.y*this.height_pct;b=a/this.size_proportion.y*this.size_proportion.x;null!=this.size_x_max_pct&&
b>this.size_x_max_pct*this.parent.screen_size.x&&(b=this.parent.screen_size.x*this.size_x_max_pct,a=b/this.size_proportion.x*this.size_proportion.y);this.screen_size={x:b,y:a};a=this.parent.screen_size.x*this.pos_pct.x;a+=this.parent.screen_position.x;b=this.parent.screen_size.y*this.pos_pct.y;b+=this.parent.screen_position.y;this.screen_position={x:a,y:b}}
function JVPlayer(){this.life_amount=99999;this.score_amounts={update:5,white:500,yellow:2E3,red:-1E4,combo:1E4,fail:0};this.time_deviation=.085;this.score_update_time=.1;this.score_update_timer=0;this.level_label_timer=void 0;this.level_label_timer_max=2;this.init=function(){this.score=0;this.life=this.life_amount;this.bonus_index=this.combo=0;this.combo_finished=!1;this.difficulty_level=this.level=0;this.game_finished=this.difficulty_level_switch_ready=!1;jvgame_label_hearts.update(this.life);jvgame_update_combo_score_text();
jvgame_label_bonus.draw_bg_fill(0);jvgame_label_bonus.update_number(this.combo);this.events=[];this.level_label_timer=0};this.update_timer=function(){this.score_update_timer+=jvgame_time_delta;this.score_update_timer>=this.score_update_time&&(this.score_update_timer=0,this.score_update(this.score_amounts.update));this.level_label_timer+=jvgame_time_delta;if(this.level_label_timer>=this.level_label_timer_max){var a=map(jvgame_player.score,midi_manager.current_song.level_scores[jvgame_player.level-
1],midi_manager.current_song.level_scores[jvgame_player.level],0,1);a=Math.min(a,1);a=Math.max(a,0);jvgame_label_level.draw_bg_fill(a)}};this.score_update=function(a){if(!this.game_finished){this.score+=a;0>this.score&&(this.score=0);a=midi_manager.get_current_song();this.level<=a.level_scores.length-1&&this.score>=a.level_scores[this.level]&&this.level_update(1);if(this.difficulty_level+1<a.difficulty_switch_scores.length&&(a=a.difficulty_switch_scores[this.difficulty_level+1],this.score>=a)){this.difficulty_level++;
var b=new JVEvent(jvaudio_get_current_timestamp());b.difficulty_level_change(this.difficulty_level,a,midi_manager.get_current_song().tracks[this.difficulty_level].current_timestamp_index);b.submit();console.log("\u2795 Switching difficulty level to: "+this.difficulty_level);for(a=0;a<jvgame_pool_pills.length;a++)jvgame_pool_pills[a].flag_crossed||(jvgame_pool_pills[a].flag_misplaced=!0)}jvgame_label_score.update_number(this.score)}};this.life_update=function(a){this.game_finished||(this.life+=a,jvgame_label_hearts.update(this.life),
0>=this.life&&(this.game_finished=!0,jvmain_set_score(this.score),jvgame_stop()))};this.combo_update=function(a){if(!this.game_finished){this.combo+=a;jvgame_label_bonus.update_number(this.combo);this.combo_finished||(a=0==this.bonus_index?0:midi_manager.get_current_song().bonus_data[this.bonus_index-1].combo,a=map(this.combo,a,midi_manager.get_current_song().bonus_data[this.bonus_index].combo,0,1),jvgame_label_bonus.draw_bg_fill(a));if(!this.combo_finished&&this.combo>=midi_manager.get_current_song().bonus_data[this.bonus_index].combo){a=
midi_manager.get_current_song().bonus_data[this.bonus_index].score;this.score_update(a);var b=new JVEvent(jvaudio_get_current_timestamp());b.combo_complete(midi_manager.get_current_song().bonus_data[this.bonus_index].combo,a);b.submit();this.bonus_index<midi_manager.get_current_song().bonus_data.length&&(this.bonus_index++,this.combo_finished||this.bonus_index!=midi_manager.get_current_song().bonus_data.length||(this.combo_finished=!0));jvgame_update_combo_score_text();jvgame_show_combo_feedback(!0,
a);jvgame_label_bonus.draw_bg_fill(0)}b=new JVEvent(jvaudio_get_current_timestamp());b.debug("client combo: "+jvgame_player.combo);b.submit()}};this.combo_reset=function(){this.game_finished||(this.combo=0,jvgame_label_bonus.update_number(this.combo),this.bonus_index=0,jvgame_update_combo_score_text(),jvgame_label_bonus.draw_bg_fill(0))};this.level_update=function(a){if(!(this.game_finished||this.level>=midi_manager.get_current_song().level_scores.length-1)){this.level+=a;a=new JVEvent(jvaudio_get_current_timestamp());
a.level_change(this.level,midi_manager.get_current_song().level_scores[this.level]);a.submit();jvgame_label_level.update_number(this.level);jvgame_sprite_ui_circle.alpha=1;var b=Math.floor(this.level/midi_manager.get_current_song().level_scores.length*(jvgame_color_circle_array.length-1));a=Math.floor(Math.max(this.level-1,0)/midi_manager.get_current_song().level_scores.length*(jvgame_color_circle_array.length-1));b=jvgame_color_circle_array[b];jvanimation_add(jvanimation_circle_color(_colorHexToRgb(jvgame_color_circle_array[a]),
_colorHexToRgb(b)));jvgame_current_circle_color=_colorHexToRgb(b);1!=this.level&&jvanimation_add(jvanimation_level_ring())}};this.add_event=function(a){this.events.push(a)}}
function JVComboFeedback(){this.parent=this;this.init=function(){this.font_size=jvgame_element_debug_anchor_area.screen_size.x/15;this.message=this.text=new PIXI.Text(" ",{fontFamily:"UniSans",fontSize:this.font_size,fill:jvgame_color_combo_feedback_positive,align:"center",dropShadow:!0,dropShadowColor:"rgba(0, 0, 0, 1)",dropShadowBlur:10,dropShadowDistance:0});this.message.position.set(jvgame_anchor_combo_feedback.x,jvgame_anchor_combo_feedback.y);this.message.rotation=-.2;this.message.anchor.set(.55,
.5);stage.addChild(this.message)};this.show=function(a,b){var c=" "+jvgame_copy.get_feedback(a)+" ";0!=b&&(c=c+"\n"+(a?"+":"")+b);this.message.text=c;this.message.style.fill=a?jvgame_color_combo_feedback_positive:jvgame_color_combo_feedback_negative;jvanimation_add(jvanimation_combo_feedback_show(this.parent))};this.stop=function(){this.message.text=""}}
function JVNumberBubble(){this.bubble=this.label_text=this.container=void 0;this.screen_element=jvgame_element_label_number_bubble;this.init=function(a,b){this.container=new PIXI.Container;this.bubble=new PIXI.Sprite(PIXI.TextureCache["ui_bubble.png"]);jvgame_setup_single_sprite(jvgame_element_label_number_bubble,this.bubble);this.bubble.position.set(a.x,a.y);this.container.addChild(this.bubble);this.label_text=new PIXI.Text(b,{fontFamily:"UniSans",fontSize:.7*this.screen_element.screen_size.x,fill:jvgame_color_bubble_text});
this.label_text.anchor.set(.5,.5);this.label_text.position.set(a.x,.02*-this.screen_element.screen_size.y);this.container.addChild(this.label_text);stage.addChild(this.container)};this.update_text=function(a){this.label_text.text=a};this.trigger_bubble=function(){}}
function JVScoreLabel(a,b,c){this.container=void 0;this.screen_element=a;this.label_text=void 0;this.label_text_content=c;this.lable_bg_fill=this.label_bg=void 0;this.bubble_number=b;this.number_dots=this.bubbles=void 0;this.init=function(){this.container=new PIXI.Container;this.label_text=new PIXI.Text(c,{fontFamily:"UniSans",fontSize:.2*jvgame_element_label_bg.screen_size.x,fill:jvgame_color_text});this.label_text.anchor.set(.5,.5);this.label_bg=new PIXI.Graphics;var a=jvgame_element_label_bg.screen_size.x,
e=jvgame_element_label_bg.screen_size.y,f=jvgame_element_label_bg_slant.screen_size.x;this.label_bg.beginFill(jvgame_color_label_bg);this.label_bg.drawPolygon([0-a/2+f,0-e/2,0+a/2+f,0-e/2,0+a/2+f,0+e/2,0-a/2-f,0+e/2]);this.label_bg.endFill();this.label_bg_fill=new PIXI.Graphics;this.container.addChild(this.label_bg);this.container.addChild(this.label_text);this.number_dots=new PIXI.Container;this.bubbles=[];for(a=0;a<b;a++)e=.6*jvgame_element_label_bg.screen_size.x+a*jvgame_element_number_bubble_margin.screen_size.x,
this.bubbles[a]=new JVNumberBubble,this.bubbles[a].init({x:e,y:0},0),this.container.addChild(this.bubbles[a].container),3<b&&a<b-1&&0==a%3&&(f=new PIXI.Text(".",{fontFamily:"UniSans",fontSize:.7*jvgame_element_label_number_bubble.screen_size.x,fill:jvgame_color_bubble_text}),f.position.set(e+jvgame_element_number_bubble_margin.screen_size.x/2.5,.5*-jvgame_element_label_number_bubble.screen_size.y),this.number_dots.addChild(f));this.container.position.set(this.screen_element.screen_position.x-this.container.width/
2+jvgame_element_label_bg.screen_size.x/2,this.screen_element.screen_position.y);this.container.addChild(this.number_dots);stage.addChild(this.container)};this.init(a,c);this.update_number=function(a){a=(""+a).split("");if(a.length<this.bubble_number)for(var b=this.bubble_number-a.length,c=0;c<b;c++)a.unshift("0");for(c=0;c<this.bubble_number;c++)this.bubbles[c].label_text!=a[c]&&(this.bubbles[c].update_text(a[c]),this.bubbles[c].trigger_bubble())};this.draw_bg_fill=function(a){this.container.removeChild(this.label_bg_fill);
this.label_bg_fill=new PIXI.Graphics;var b=jvgame_element_label_bg.screen_size.x*a,c=jvgame_element_label_bg.screen_size.y,d=-jvgame_element_label_bg.screen_size.x/2+b/2,h=jvgame_element_label_bg_slant.screen_size.x;0==a&&(h=0);this.label_bg_fill.beginFill(jvgame_color_label_fill);this.label_bg_fill.drawPolygon([d-b/2+h,0-c/2,d+b/2+h,0-c/2,d+b/2+h,0+c/2,d-b/2-h,0+c/2]);this.label_bg_fill.endFill();this.container.addChild(this.label_bg_fill);this.container.removeChild(this.label_text);this.container.addChild(this.label_text);
this.container.removeChild(this.bubbles[0].container);this.container.addChild(this.bubbles[0].container)}}
function JVHeartLabel(a,b){this.container=void 0;this.screen_element_area=a;this.hearts=[];this.heart_amount=3;this.init=function(){this.container=new PIXI.Container;for(var a=this.screen_element_area.screen_size.x/(this.heart_amount-1),b=0;b<this.heart_amount;b++)this.hearts[b]=new PIXI.Sprite(PIXI.TextureCache["ui_heart.png"]),this.hearts[b].anchor.set(.5,.5),this.hearts[b].position.set(b*a,0),this.hearts[b].width=jvgame_element_heart.screen_size.x,this.hearts[b].height=jvgame_element_heart.screen_size.y,
this.container.addChild(this.hearts[b]);this.container.position.set(jvgame_element_heart_area.screen_position.x-jvgame_element_heart_area.screen_size.x/2,jvgame_element_heart_area.screen_position.y);stage.addChild(this.container)};this.init();this.update=function(a){for(var b=0;b<this.heart_amount;b++)this.hearts[b].alpha=b<a?1:.3}}
function JVCopy(){this.language_index=LANG_ID;this.content=[{label:"score",copy:["Score","Score"]},{label:"niveau",copy:["Level","Niveau"]},{label:"bonus",copy:["Bonus","Bonus"]}];this.get=function(a,b){null==b&&(b=this.language_index);for(var c="",d=0;d<this.content.length;d++)if(this.content[d].label==a){c=this.content[d].copy[b];break}return c};this.feedback_index_negative=this.feedback_index_positive=-1;this.feedback={positive:["Perfect!;Cool;Goed gespeeld;Top;Wat een tempo!;Mooi;Wauw!;Super!;Geweldig!".split(";"),
"Parfait !;Cool !;Bien jou\u00e9;Top;Quel rythme !;Joli;Top fort !;Super !;G\u00e9nial !".split(";")],negative:["Jammer;Bijna;Je kan het!;Volhouden;Verdorie;Volgende keer beter;Niet cool;Een misser!".split(";"),"Dommage;Presque;Tu peux le faire;Courage;Zut;Pas de chance;Pas cool;Rat\u00e9".split(";")]};this.get_feedback=function(a,b){null==b&&(b=this.language_index);if(a){this.feedback_index_positive=(this.feedback_index_positive+1)%this.feedback.positive[b].length;var c=this.feedback.positive[b][this.feedback_index_positive]}else this.feedback_index_negative=
(this.feedback_index_negative+1)%this.feedback.negative[b].length,c=this.feedback.negative[b][this.feedback_index_negative];return c}}
function JVCountdownNumber(){this.init=function(){this.text=new PIXI.Text("",{fontFamily:"UniSans",fontSize:jvgame_element_countdown_number.screen_size.y,fill:jvgame_color_countdown});this.text.anchor.set(.5,.5);this.text.position.set(jvgame_element_countdown_number.screen_position.x,jvgame_element_countdown_number.screen_position.y);this.text.scale.set(0,0)};this.begin=function(){this.countdown_amount=3;this.countdown_index=0;this.beat_length=midi_manager.get_current_song().beat_length;this.counter=
-.25;this.jump_length=this.beat_length/1;this.jump_amount=9;this.jump_counter=this.jump_index=0;stage.addChild(this.text);this.isActive=!0;jvgame_sprite_ui_tictacbox.position.set(jvgame_element_ui_tictacbox.screen_position.x,jvgame_element_ui_tictacbox.screen_position.y)};this.stop=function(){stage.removeChild(this.text);this.isActive=!1};this.update=function(){this.isActive&&(this.counter+=Math.min(jvgame_time_delta,.02),this.jump_counter+=Math.min(jvgame_time_delta,.02),this.jump_counter>=this.jump_length/
2*this.jump_index&&(this.jump_index++,1<this.jump_index&&jvaudio_play_shake(),jvanimation_add(jvanimation_tictac_jump_3(1))),this.counter>=this.beat_length*this.countdown_index&&(this.countdown_index<this.countdown_amount?(this.text.text=this.countdown_amount-this.countdown_index,this.trigger()):this.countdown_index==this.countdown_amount&&(this.isActive=!1,jvanimation_add(jvanimation_tictac_dissapear())),this.countdown_index++))};this.trigger=function(){jvanimation_add(jvanimation_countdown_number())}}
function JVParticle(){this.last_update_framecount=0;this.init=function(){this.active=!1;this.sprite=new PIXI.Sprite(PIXI.TextureCache["particle_bubble.png"]);this.sprite.anchor.set(.5,.5);this.a=this.v=this.pos=void 0};this.spawn=function(a,b){this.active=!0;this.speed=50+100*Math.random();this.life=.5+.5*Math.random();this.counter=0;this.pos=a;this.v={x:Math.cos(b)*this.speed,y:Math.sin(b)*this.speed};var c=-1.57075+b+3.1415*Math.random();this.a={x:20*Math.cos(c),y:20*Math.sin(c)};this.speed=1+Math.random();
this.sprite.position.set(this.pos.x,this.pos.y);this.sprite.alpha=.5+Math.random()/2};this.update=function(){if(this.active){this.counter+=jvgame_time_delta;this.v.x+=this.a.x*this.counter;this.v.y+=this.a.y*this.counter;this.pos.x+=this.v.x*this.speed*jvgame_time_delta;this.pos.y+=this.v.y*this.speed*jvgame_time_delta;this.sprite.position.set(this.pos.x,this.pos.y);var a=1-this.counter/this.life;this.sprite.width=jvgame_element_particle_bubble.screen_size.x*a;this.sprite.height=jvgame_element_particle_bubble.screen_size.y*
a}}}
function JVParticleManager(){this.particle_burst_amount=20;this.particle_pool_size=2;this.init=function(){this.container=new PIXI.ParticleContainer(this.particle_burst_amount*this.particle_pool_size,{scale:!0,position:!0,rotation:!1},this.particle_burst_amount*this.particle_pool_size);stage.addChild(this.container);this.particles=[];for(var a=this.current_pool_index=0;a<this.particle_burst_amount*this.particle_pool_size;a++){var b=new JVParticle;b.init();this.particles.push(b)}};this.trigger=function(){this.current_pool_index=
(this.current_pool_index+1)%this.particle_pool_size;for(var a=0;a<this.particle_burst_amount;a++){var b=this.particle_burst_amount*this.current_pool_index+a,c=jvgame_element_particle_origin.screen_position,d=jvgame_element_particle_origin.screen_size,e=6.283*Math.random();this.particles[b].spawn({x:c.x+Math.cos(e)*d.y,y:c.y+Math.sin(e)*d.y},e);this.container.addChild(this.particles[b].sprite)}};this.update=function(){for(var a=0;a<this.particles.length;a++)this.particles[a].active&&(this.particles[a].update(),
this.particles[a].counter>=this.particles[a].life&&(this.particles[a].active=!1,this.container.removeChild(this.particles[a].sprite)))};this.stop=function(){for(var a=0;a<this.particles.length;a++)this.particles[a].active=!1,this.container.removeChild(this.particles[a].sprite)}}
function JVEvent(a){this.timestamp=a;this.properties=this.type=void 0;this.user_tap=function(a,c,d,e,f,g){this.type="ut";this.properties={ph:a,pt:e,dl:d,pi:c,pts:f,pm:g?1:0,cv:0}};this.pill_missed=function(a,c,d){this.type="pm";this.properties={dl:a,pi:c,pm:d?1:0,cv:0}};this.combo_complete=function(a,c){this.type="cc";this.properties={ca:a,cr:c,cv:0}};this.level_change=function(a,c){this.type="lc";this.properties={nl:a,ls:c,cv:0}};this.difficulty_level_change=function(a,c,d){this.type="dlc";this.properties=
{ndl:a,dss:c,ntsi:d,cv:0}};this.debug=function(a){this.type="d";this.properties={m:a,cv:0}};this.submit=function(){jvgame_player.add_event({ts:this.timestamp,t:this.type,p:this.properties})}}
function JVScoreText(){this.follow_pill=this.score_text=this.score_amount=this.flag_finished=this.flag_spawned=void 0;this.init=function(){this.flag_finished=this.flag_spawned=!1;this.score_text=new PIXI.Text("test",{fontFamily:"UniSans",fontSize:.3*jvgame_element_pill.screen_size.y,fill:0});this.score_text.position.set(500,500)};this.spawn=function(a){this.flag_spawned=!0;this.flag_finished=!1;this.follow_pill=a;switch(this.follow_pill.type){case 0:this.score_amount=jvgame_player.score_amounts.white;
break;case 1:this.score_amount=jvgame_player.score_amounts.yellow;break;case 2:this.score_amount=jvgame_player.score_amounts.red}a="";0<=this.score_amount&&(a="+"+this.score_amount);0>this.score_amount&&(a="-"+this.score_amount);this.score_text.text=a;stage.addChild(this.score_text)};this.update=function(){this.score_text.position.set(this.follow_pill.position.x,this.follow_pill.position.y);this.follow_pill.flag_crossed&&(console.log("flag death animation playing"),this.kill())};this.kill=function(){console.log("SCORE TEXT FINISH");
this.flag_finished=!0;stage.removeChild(this.score_text)}}
function JVScoreTextManager(){this.finished=!1;this.score_text_red=this.score_text_yellow=this.score_text_white=void 0;this.init=function(){this.score_text_white=new JVScoreText;this.score_text_white.init();this.score_text_yellow=new JVScoreText;this.score_text_yellow.init();this.score_text_red=new JVScoreText;this.score_text_red.init()};this.spawn_score_text=function(a){switch(a.type){case 0:this.score_text_white.spawn(a);this.flag_white_spawned=!0;break;case 1:this.score_text_yellow.spawn(a);this.flag_yellow_spawned=
!0;break;case 2:this.score_text_red.spawn(a),this.flag_red_spawned=!0}};this.update=function(){this.finished||(this.score_text_white.flag_spawned&&!this.score_text_white.flag_finished&&this.score_text_white.update(),this.score_text_yellow.flag_spawned&&!this.score_text_yellow.flag_finished&&this.score_text_white.update(),this.score_text_red.flag_spawned&&!this.score_text_red.flag_finished&&this.score_text_red.update(),this.score_text_white.flag_finished&&this.score_text_white.flag_finished&&this.score_text_white.flag_finished&&
(console.log("\ud83d\udd23 setting score text manager finished to true"),this.finished=!0))};this.check_if_spawned=function(a){if(!this.finished)switch(a.type){case 0:this.score_text_white.flag_spawned||this.score_text_white.spawn(a);break;case 1:this.score_text_yellow.flag_spawned||this.score_text_yellow.spawn(a);break;case 2:this.score_text_red.flag_spawned||this.score_text_red.spawn(a)}}}
function map(a,b,c,d,e,f){null!=f&&(f="map("+a+", "+b+", "+c+", "+d+", "+e+")",a>c&&(f+=" OUT OF BOUNDS"),console.log(f));return d+(e-d)*(a-b)/(c-b)}function _interpolateColor(a,b,c){for(var d=a.slice(),e=0;3>e;e++)d[e]=Math.round(d[e]+c*(b[e]-a[e]));return d}function _colorRgbToHex(a){for(var b="0x",c=0;c<a.length;c++)16>a[c]&&(b+="0"),b+=a[c].toString(16);return b}function _colorHexToRgb(a){return[a>>16&255,a>>8&255,a&255]};